CREATE DATABASE EMPLOYEE;

USE EMPLOYEE;

CREATE TABLE EMPLOYEE(
    EMP_ID INT PRIMARY KEY , 
    EMP_NAME VARCHAR(100) NOT NULL,
    MANAGER_ID INT NULL,
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE (EMP_ID));
  
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, MANAGER_ID) VALUES 
(1,'SARA',NULL),
(2,'BOB',1),
(3,'RAINA',2),
(4,'SATZ',3),
(5,'KRISH',3);

//1
SELECT e.EMP_NAME AS EMPLOYEE , m.EMP_NAME AS MANAGER
FROM EMPLOYEE e
LEFT JOIN EMPLOYEE m ON e.MANAGER_ID = m.EMP_ID; 

//2
SELECT EMP_NAME 
FROM EMPLOYEE
WHERE MANAGER_ID = (SELECT EMP_ID FROM EMPLOYEE WHERE EMP_NAME = 'RAINA');

//3
SELECT m.EMP_NAME AS MANAGER ,  COUNT(e.EMP_ID) AS REPORT 
FROM EMPLOYEE e
JOIN EMPLOYEE m ON e.MANAGER_ID = m.EMP_ID
GROUP BY m.EMP_NAME;  

//4
SELECT EMP_NAME
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL; 
 
//5
WITH RECURSIVE EMP_HIERARCHY AS (
    SELECT EMP_ID, EMP_NAME, MANAGER_ID, 1 AS LEVEL
    FROM EMPLOYEE
    WHERE MANAGER_ID IS NULL  

    UNION ALL

    SELECT e.EMP_ID, e.EMP_NAME, e.MANAGER_ID, eh.LEVEL + 1
    FROM EMPLOYEE e
    INNER JOIN EMP_HIERARCHY eh ON e.MANAGER_ID = eh.EMP_ID
)
SELECT EMP_NAME, MANAGER_ID, LEVEL FROM EMP_HIERARCHY ORDER BY LEVEL, MANAGER_ID; 
