CREATE DATABASE CUSTOMER;

USE CUSTOMER;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(100)  
);

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
ORDER_DATE DATE,   
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)  
);

INSERT INTO CUSTOMERS(CUSTOMER_ID,CUSTOMER_NAME) VALUES
(1,'SARA'),
(2,'SATZ'),
(3,'KRISH'),
(4,'RAINA');

INSERT INTO ORDERS(ORDER_ID,CUSTOMER_ID,ORDER_DATE) VALUES
(1,1,'2024-01-10'),
(2,2,'2025-01-22'),
(3,3,'2024-01-15'),
(4,3,'2025-01-28'),
(5,3,'2025-01-29');


//1
SELECT O.ORDER_ID
FROM ORDERS O
JOIN CUSTOMERS C ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.CUSTOMER_NAME = 'KRISH';

//2
SELECT C.CUSTOMER_NAME
FROM CUSTOMERS c 
JOIN ORDERS O ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
HAVING COUNT(O.ORDER_ID)>1; 


//3
SELECT C.CUSTOMER_NAME , COUNT(O.ORDER_ID) AS ORDERCOUNT
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME;


//4
SELECT C.CUSTOMER_NAME
FROM CUSTOMERS C 
LEFT JOIN ORDERS O ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;    

//5
SELECT C.CUSTOMER_NAME , MAX(O.ORDER_DATE) AS RECENTORDER
FROM CUSTOMERS C 
LEFT JOIN ORDERS O ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME; 


